title: Lin Kyi
url: "https://lin-kyi.github.io"
baseurl: "/"
#remote_theme: ankitsultana/researcher@gem

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Publications"
   link: "/publications"
 - name: "Talks"
   link: "/talks-media"
 - name: "Teaching & Supervision"
   link: "/teaching-supervision"
 - name: "Service"
   link: "/service"
 - name: "Random"
   link: "/random"
