title: Researcher
url: "https://lin-kyi.github.io"
baseurl: "/"
remote_theme: ankitsultana/researcher@gem

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Publications"
   link: "/publications"
 - name: "Talks and Media"
   link: "/talks-media"
 - name: "Teaching and Supervision"
   link: "/teaching-supervision"
 - name: "service"
   link: "/service"
